### PR TITLE
fix(crash):  try to upload a file that will overflow the disk size

### PR DESCRIPTION
**Pull request by 0xSaurabhx**
This is a PR for Bug #617 

So, Whats Changed?

**Check Disk Space Before Upload:** Before starting the upload, check if there is enough disk space available.
**Retry Mechanism:** Implement a retry mechanism that attempts to upload the file a limited number of times.
**Clean Up Failed Uploads:** Ensure that failed uploads are cleaned up properly to free up disk space.

### CODE REVIEW

**Comment by stonith404** [comment]
Thanks for your contribution, that's a good addition. 

I'm not sure if the the retry mechanism is necessary on the backend though. The frontend already retries if a chunk can't get uploaded. I think it would make more sense to stop the retry mechanism in the frontend if the backend returns that the disk is full.

What do you think?

**Comment by 0xSaurabhx** [comment]
@stonith404 Hey,

I guess the more secure way to handle these things, is on the backend itself. 

Also as you said I will update the frontend too.

**Comment by stonith404** [comment]
@0xSaurabhx What would make the retry logic more secure if it is done on the backend?

I don't really see a use case for the backend retry logic because if these steps fail in the backend, it will most likely fail the next time.

If we do the retry logic in the frontend all possible errors get handled like internet connection issues on the client side and backend errors aswell.

**Comment by stonith404** [comment]
Do you still plan to work on this PR or should I close it?

**Pull request closed without merging**
