### PR TITLE
Fixed russian translation file

### PR DESCRIPTION
**Pull request by ManjTi**

### CODE REVIEW

**Comment by stonith404** [comment]
Hey thanks for your contribution. What exactly does this PR do? I saw that you successfully translated Pingvin Share to Russian on Crowdin.

**Comment by ManjTi** [comment]
> Hey thanks for your contribution. What exactly does this PR do? I saw that you successfully translated Pingvin Share to Russian on Crowdin.

Seems like you used original english file instead of translated one in the ru-RU.ts file

**Comment by stonith404** [comment]
Ah yeah that's the source file. All translations go to the branch `i18n_crowdin` and then Crowdin automatically creates a pull request. The file `ru-RU.ts` is still in English because I didn't merge the changes of Crowdin yet.

**Comment by ManjTi** [comment]
Ok thanks for explanation, closing.

**Comment by stonith404** [comment]
👍 I'm trying to merge your translations but I have some issues with Crowdin at the moment.

**Pull request closed without merging**
