### PR TITLE
docs: improve stand-alone upgrade guide

### PR DESCRIPTION
**Pull request by iUnstable0**

### CODE REVIEW

**Comment by stonith404** [comment]
Thanks for your contribution, that's a lot cleaner solution. I'm not really experienced in `pm2` but I've just tested it and noticed that stopping the frontend and backend isn't necessary. Do you think we could remove this step?

**Comment by iUnstable0** [comment]
yeah sure but i've had bad experiences with not stopping running apps while building so don't really know but if you;ve tested it and it works fine then yeah remove it i guess :D

**Comment by iUnstable0** [comment]
also sorry for not following the contributing guide 😅

**Comment by stonith404** [comment]
Okay, if you have made these experiences it's probably better to stop it first. Thanks again for your contribution :)

**Pull request merged**
