### PR TITLE
doc: add Railway.app deployment

### PR DESCRIPTION
**Pull request by YunchaoZheng**
View deployment from Railway:
https://pingvin-demo-production-8dd1394.up.railway.app

This Git commit includes an update to the README.md file, which adds instructions for deploying with Railway. The instructions include detailed steps for both one-click and manual deployment, as well as links and images. The commit contains two patches, one to fix a spelling error in the README.md file, and another to add detailed deployment instructions for Railway to the README.zh-cn.md file, as well as correcting a spelling error. An appropriate commit message might be "Add Railway deployment guide and fix spelling errors". The content of this commit is aimed at explaining how to use the Railway deployment platform, making it easier for users to deploy their projects quickly, and improving the quality of the documentation by fixing spelling errors.

该 Git 提交包括 README.md 文件的更新，添加了关于使用 Railway 部署的说明。其中提供了一键部署和手动部署的详细操作步骤，并附带了链接和图片。该提交中包含了两个补丁，一个是修复了 README.md 文件中的错误拼写，另一个是在 README.zh-cn.md 文件中添加了使用 Railway 部署的详细步骤，并修正了一个错误的拼写。适当的提交信息可能是 "Add Railway deployment guide and fix spelling errors" (添加了 Railway 部署指南和修正拼写错误)。该次提交的内容是介绍如何使用 Railway 部署平台，方便用户快速部署项目，并且修复了一些拼写错误，提高了文档质量。

### CODE REVIEW

**Comment by stonith404** [comment]
Hey, thanks for your contribution! I've just tested your template and I noticed that the database and files are not persistent. E.g if I redeploy Pingvin Share all users and shares get cleared. I'm not experienced in Railway but do you know if Railway supports persistent volumes?

**Comment by YunchaoZheng** [comment]
Here are some ways to persist data:

Database

1. Railway provides support for various databases such as PostgreSQL, Redis, MongoDB, and MySQL.
2. Alternatively, you can use an outside database provider like Mongo Atlas. However, migrating the current database to a different structure may be necessary.
3. Deploy Prisma as another production environment in the same Railway project manually, expose the DB connection parameters into the pingvin environments.

File
Amazon S3 API support, and that's how [Send](https://github.com/timvisee/send) stores files.

If we deploy on an edge compute platform like Railway, adding S3 support will be the most important step since Railway provides limited disk space and memory.

**Comment by stonith404** [comment]
Hmm okay so yeah S3 storage would be nice in this case. I'm not sure how difficult this is to implement as I don't use AWS. 
Pingvin Share uses SQLite, so this could get really difficult. We could store the SQLite file on S3 but this could hurt the performance and it could get expensive too as this would require many reads. Do you have a better idea?

**Comment by YunchaoZheng** [comment]
Get it. I think we can deal the database and the files in separate ways:

## Database
Use Railway provided databases (MySQL, PostgreSQL, Redis, Mongo) or Mongo Atalas (Cluster) as alternative for SQLite. 

> This requires more work and will change the current app structure. 

I will work on this first to ensure database persistence.

## File
With limited life cycle of the (uploaded) files, we can use S3 bucket as cache to store (uploaded) files temporally, here's the docs of [AWS s3 JavaScript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html). 

> S3 is currently supported by many cloud service providers. Take an example, Cloudflare provides 10GB/Month free bucket with fair share bandwidth. 

I will work on adding S3 feature if time is available.

**Mounting cloud drive (But I not suggested do so)
Mounting personal cloud drive, e.g. OneDrive, as a disk to store (uploaded) files is another choice, which will not change current project structure and easy to get started. 

> But it required third-party tools, more work for *deployers* when deploying the forks, especially on cloud platforms. Moreover, it might violate the cloud drive agreements.

**Comment by stonith404** [comment]
We still have to support SQLite to enable an easy installation with Docker. Maybe there is a way to configure Prisma that the user can choose the database but this could get really difficult as [Prisma doesn't support generic database migrations](https://www.prisma.io/docs/concepts/components/prisma-migrate/prisma-migrate-limitations-issues#you-cannot-automatically-switch-database-providers).

> With limited life cycle of the (uploaded) files, we can use S3 bucket as cache to store (uploaded) files temporally, here's the docs of [AWS s3 JavaScript SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/index.html).

What exactly do you mean with "we can use S3 bucket as cache to store (uploaded) files temporally"? Where would you store the files permanently then?

**Comment by YunchaoZheng** [comment]
OK, I will try to use docker-compose to separate SQLite from the all-in-one docker image next step.

I meant that we could use

-  local drive
-  S3 bucket (only if set S3*** ENVs)

to store uploaded files. All files with life cycle limit or just permanent.

If we deploy on cloud, using S3 would benefit a lot since cloud platform offers quite limited disk space.

Since this PR is not appropriate to be merged currently, I will close it and make an issue instead. How about that?

**Comment by stonith404** [comment]
Yep, let's create an issue👍

**Pull request closed without merging**
