### PR TITLE
doc: add Zeabur installation guide

### PR DESCRIPTION
**Pull request by yuaanlin**
This Pull Request introduce a link of installation guide to deploy Pingvin Share on [Zeabur](https://zeabur.com).

[Deploy on Zeabur](https://zeabur.com/templates/19G6OK)

And there is a YouTube video shows how the deploy steps look like:

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=JOhWUvSSJYQ)

### CODE REVIEW

**Comment by stonith404** [comment]
This looks interesting. How does Zeabur handle the persistence of the files and the SQLite database?

**Comment by yuaanlin** [comment]
> This looks interesting. How does Zeabur handle the persistence of the files and the SQLite database?

Zeabur will mount a persistent volume on `/opt/app/backend/data`.

Ref: https://github.com/zeabur/zeabur/blob/main/prebuilts/pingvin-share.toml#L18

**Comment by stonith404** [comment]
Nice, Zeabur looks great :)
The installation video you added is a nice addition. However, I prefer not to promote non-open-source projects in the README. Could you please remove the 'Deploy on Zeabur' button?

**Comment by stonith404** [comment]
Sorry, I meant the link to the template is fine. Just remove the button please.

**Comment by yuaanlin** [comment]
> Sorry, I meant the link to the template is fine. Just remove the button please.

Sure! The button is removed. https://github.com/stonith404/pingvin-share/pull/447/commits/a15ec23b1941a33596e3ce18086848c2025dd5e6

**Pull request merged**
