### PR TITLE
Switch to Alpine image

### PR DESCRIPTION
**Pull request by comassky**
Tested with Ubuntu 22.04.1 (build & deploy)

No tested with ARM

### CODE REVIEW

**Comment by stonith404** [comment]
Hey, thank you for your PR, really appreciate that! Unfortunately alpine doesn't work with Prisma ORM:
```
#0 5.314 Error: Unable to establish a connection to query-engine-node-api library. It seems that the current architecture arm64 is not supported, or that libc is missing from the system.
#0 5.314 Details: Unable to require(`/opt/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node`)
#0 5.314  Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /opt/app/node_modules/prisma/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
```
I'm not really sure why, but there must be software that is installed on the slim image but not on the alpine. Maybe you find a solution or else we must stick to the alpine image...

Btw you can test builds for arm with buildx, it's a built-in tool of docker:
`docker buildx build --tag stonith404/pingvin-share:development --platform linux/arm64 .`

**Comment by comassky** [comment]
@stonith404 

Thanks for your reactivity

Never used buildx before

image

**Comment by comassky** [comment]
libc is not installed on alpine image, gcompat package seems to resolve libc (glibc) issue.

apk add gcompat

**Comment by stonith404** [comment]
Still fails for me when adding `apk add gcombat`

**Comment by comassky** [comment]
Ok, so sad !

I close the PULL REQUEST

**Pull request closed without merging**
