### PR TITLE
feat(auth): auto redirect to OAuth provider

### LINKED ISSUE #329: 🚀 Feature: Allow admins to disable "built-in" auth and force specific IDP
### 🔖 Feature description

Allow the administrator to disable the "built-in" accounts (and hide the username / password fields) and if only one social connector is enabled automatically redirect to the relevant IDPs auth flow. 

The user should then also be able to create an account using the idp auth flow sign in request on successful sign in if they don't already have an account.

### 🎤 Pitch

I use SSO for all of my public / client facing services having the ability to hide other authentication methods and redirect the user automatically to the sign-in page if only one method is enabled would improve the user experience sign-in flow.

### PR DESCRIPTION
**Pull request by zz5840**
Make it possible to disable signing in with password and add automatically redirect users to OAuth provider.

close #329

### CODE REVIEW

**Comment by zz5840** [comment]
It's confusing that the `allow-registration` is in the share category, so I add a `allow-registration` config in the new account category, but I haven't migrated the old config to this.

Should I do the migration or leave it in share category?

**Comment by stonith404** [comment]
@zz5840 Yeah I think it would make sense to migrate it to the new account category.

You first have to create a migration with `npx prisma migrate dev` and then manually add the migration logic to it.  If you need help with the migration let me know :)

**Comment by thelouisvivier** [comment]
Hello !

I would love this feature, any visibility on when it will be merged ?

Thanks for all the work !

**Comment by thelouisvivier** [comment]
@zz5840 Ok Nice ! Do you need any help on something specific ?

**Comment by zz5840** [comment]
@thelouisvivier Oh thanks, it seems all that's left is the database migration, I think I can make it works this weekend.

But there's a small trouble, if home page is disabled and auto redirection to oauth provider is enabled, a user will be redirect to provider's auth page immediately when he sign out. And for some providers, confirm is omitted for users that have logged in the app before, which will cause a user can not log out the app forever. Any ideas on this?

**Comment by thelouisvivier** [comment]
@zz5840 Yes, I am using Microsoft Oauth, and I don't have any confirmation for login.
 
What I was thinking for that was : 

- an admin toggle to disable builtin auth and the associated form.

- keep the sign in page but with only the oauth button(s).

This way, users can only login through oauth, but you don't have the issue of the direct redirect you're talking about.


And the advantage of that is you can have multiple oauth providers at the same time and still be able to deactivate local accounts.

In addition, it would be nice if instead of only displaying the icon of the oauth provider, we would be able to add a name next to the icon on the login page.

Find attached a visual exemple.

image
image

What do you think ?

**Comment by zz5840** [comment]
@thelouisvivier You are right, and I have implemented what you proposed. But auto redirection to IdP is also a significant feature, right?

**Comment by zz5840** [comment]
@thelouisvivier The option for auto-redirection is also implemented, so should we ignore this problem and just leave a warning to admin?

**Comment by thelouisvivier** [comment]
@zz5840 I think it's the best you cans do yes. A warning next to the parameter and in the documentation. 👍

**Comment by thelouisvivier** [comment]
Hey @zz5840 ! Happy new year !
Did you find time to achieve the functionality ?

If you need help for testing, let me know !

**Comment by zz5840** [comment]
@zz5840 Oh, maybe this weekend. You can pull and run it if you want to test.

**Comment by thelouisvivier** [comment]
Hey @zz5840 Just tested a bit this version.

I spotted a bug : the option "Allow registration" is present on "Account" config page, but also on "Share" config page. And the one really working to disable/enable the registration is the one in the "Share" config page.

Screenshot 2024-01-12 at 09 51 19
-48de-9ca9-20ec919fdcfc">

Also, I don't understand the purpose of the "Allow registration" option in the Social Login page : 
Screenshot 2024-01-12 at 09 53 34

I couldn't test the authentication flow on my test environment because I don't have Oauth configured on it.

Otherwise, it seems very promising !

**Comment by thelouisvivier** [comment]
I was just thinking, could we also allow password authentication but just for the admin ? 
This way, if the OAuth is not working, an admin can still access the configuration pages and fix any issues ?

**Comment by mobiledude** [comment]
this is how Immich implemented this. Love your app btw :-)

Auto Launch
When Auto Launch is enabled, the login page will automatically redirect the user to the OAuth authorization url, to login with OAuth. To access the login screen again, use the browser's back button, or navigate directly to /auth/login?autoLaunch=0.

**Comment by thelouisvivier** [comment]
@mobiledude oh great, that's good to know. I will wait on final implementation then ! Thanks

**Comment by MattyMay** [comment]
Any update on this or help needed? This is a feature I would really like, and am happy to contribute or help test anything.

> When Auto Launch is enabled, the login page will automatically redirect the user to the OAuth authorization url, to login with OAuth. To access the login screen again, use the browser's back button, or navigate directly to /auth/login?autoLaunch=0.

This seems like a good approach.

**Comment by zz5840** [comment]
Thank you all, I think I should take some time to deal with this PR recently.



---Original---
From: "Matt ***@***.***&gt;
Date: Thu, Jul 11, 2024 14:40 PM
To: ***@***.***&gt;;
Cc: "Qing ***@***.******@***.***&gt;;
Subject: Re: [stonith404/pingvin-share] feat(auth): auto redirect to OAuthprovider (PR #343)




 
Any update on this or help needed? This is a feature I would really like, and am happy to contribute or help test anything.
  
When Auto Launch is enabled, the login page will automatically redirect the user to the OAuth authorization url, to login with OAuth. To access the login screen again, use the browser's back button, or navigate directly to /auth/login?autoLaunch=0.
  
This seems like a good approach.

**Comment by stonith404** [comment]
Do you still plan to work on this PR or should I close it?

**Comment by zz5840** [comment]
> Do you still plan to work on this PR or should I close it?

@stonith404 Sorry for late response, I'll close it now.

**Pull request closed without merging**
