### PR TITLE
Add admin-exclusive share-management page

### PR DESCRIPTION
**Pull request by SFGrenade**
Allows to view a list of all shares of all users, with the user who owns the share next to it.

Partially allows https://github.com/stonith404/pingvin-share/issues/124

### CODE REVIEW

**Comment by stonith404** [comment]
Thank you for your contribution, it's a great addition. 

I've updated the icon to match the existing share icon for consistency. Additionally, I've added the share size to the list and removed the description to avoid cluttering it.

It looks ready to merge for me, what do you think?

**Review by stonith404 — APPROVED** [review]

**Comment by SFGrenade** [comment]
It does look ready to merge for me as well

**Comment by droplinxuser** [comment]
Thanks for the great feature.
But it seems to conflict when a hosted app allows guest uploads?

image

**Comment by SFGrenade** [comment]
oh, reverse shares? i didnt account for those

**Comment by droplinxuser** [comment]
Yes, I do have some reverse shares as well.

**Comment by stonith404** [comment]
I forgot to test this as well. However, it should be fixed now in `v0.24.1`.

**Comment by droplinxuser** [comment]
> But it seems to conflict when a hosted app allows guest uploads?

This is working fine now.
Thanks a lot.

Similar request: please add pagination :).

**Comment by stonith404** [comment]
@droplinxuser Yeah, that's currently only a basic implementation. Pagination, filtering, and ordering would be nice too. Feel free to create a feature request.

**Comment by droplinxuser** [comment]
Sure, added :)
https://github.com/stonith404/pingvin-share/issues/468

**Pull request merged**
