### PR TITLE
Worked on issue  Feature Add email recipients more efficiently #500

### PR DESCRIPTION
**Pull request by RahulMishra0722**
### Now we get suggestion of past used emails
Screenshot 2024-06-20 at 1 22 48 AM

### CODE REVIEW

**Comment by stonith404** [comment]
Great, thanks for your contribution :) It seems like you linked the wrong issue (#466). Which issue should be closed by this PR?

**Comment by stonith404** [comment]
Oh, I didn't read the title. Your implementation partially closes issue #500 because it was also requested that emails can be separated with commas instead of the dropdown.

> Use Gmail-esque email form, which automatically submit an email address when typing the , (comma) symbol, so users can manually type in multiple email addresses without clicking the dropdown box all the time.

Would you like to include this feature in the current pull request, or should I merge it as it is for now?

**Comment by RahulMishra0722** [comment]
> Oh, I didn't read the title. Your implementation partially closes issue #500 because it was also requested that emails can be separated with commas instead of the dropdown.
> 
> > Use Gmail-esque email form, which automatically submit an email address when typing the , (comma) symbol, so users can manually type in multiple email addresses without clicking the dropdown box all the time.
> 
> Would you like to include this feature in the current pull request, or should I merge it as it is for now?
the latter ill add the feature separately. Thanks

**Comment by RahulMishra0722** [comment]
fixed https://github.com/stonith404/pingvin-share/pull/510#issue-2379469008

**Pull request closed without merging**
