### PR TITLE
New Feature: Granular Control of Expiration Date + 12/24 Hour Modes

### LINKED ISSUE #8: Expiration date of "Never"
It would be nice if there was an expiration date of "never" so that the share can be used at any time and manually deleted when no longer needed. If this is a feature you'd approve of, I wouldn't mind forking and creating a PR to implement it.

### LINKED ISSUE #12: More granular expiration input.
I wrote issue #8  and realized after I opened PR #11 that it would make much more sense to have even more granular expiration selection.

Something like this:
image

Based on the source code, it shouldn't be too hard to implement. Maybe I can replace PR #11 with a feature like this?

These lines could essentially stay exactly the same:
https://github.com/stonith404/pingvin-share/blob/cde22f85ee785363bb0149347a2187c9166f4cb6/backend/src/share/share.service.ts#L38-L43

Pretty much the only thing that would need to change would be:
https://github.com/stonith404/pingvin-share/blob/b30269344db456a83b846247725fa9ea242e3d94/frontend/src/components/share/CreateUploadModalBody.tsx#L102-L115

and a little bit of frontend logic.

It could even be a little more advanced, giving a preview of the exact time the share would expire:

image

What do you think?

### PR DESCRIPTION
**Pull request by stautonico**
## New Features
- Adds granular control of expiration date, being able to set a specific duration for when the share will expire (resolves #12)
image
- Adds the ability to disable the expiration date of a share (resolves #8)
- Configurable 12/24 hour selection using the frontend's `.env` file

## What changed
- Added some missing dependencies to package.json (it wouldn't run without)
- Updated rx.js
    Without updating rx,js, an error was thrown when trying to access the database. (`TypeError: (0 , rxjs_1.lastValueFrom) is not a function`)
- Replaced expiration dropdown with a numerical input and a dropdown for "unit selection" (minutes, hours, days, etc.)
- Added the "Never" expiration checkbox option to the "create share" modal (disables numerical input when checked)
- Added small tooltip under expiration selection previewing when the share would expire
- Updated text (in the completed upload modal and shares page) to match the "never" expiration (text like "this share never "expires")
- Updated backend to not automatically remove "never expires" shares
- Fixed some various linting errors (mostly related to unused imports)
- Added a new environment variable in the frontend to toggle between 12-hour and 24-hour date/time previews (used in several places)

## How was this implemented
The customizable expiration date changes required no changes to the backend, only the frontend needed some changes.

The "never" expiration date was implemented by using unix timestamp 0. Some manual exceptions were added to the backend to support the timestamp of 0. For example, `backend/src/auth/jobs/jobs.service.ts` line 20 (`AND: [{expiration: {lt: new Date()}}, {expiration: {not: moment(0).toDate()}}]`) now has a hardcoded exception to shares that have a expiration date of 0. There are several other changes very similar to this scattered around the backend.

The 12/24 hour modes was implemented by simply importing next's runtime config options and checking the `TWELVE_HOUR_TIME` option, then printing the appropriate time format.

## Known Issues
There is one known issue: entering an expiration date that is too long. Some values (`999999 Years` for example) break the date parsing in the backend. A quick fix to temporarily resolve this issue is to limit the expiration input to a smaller value (currently set to `99999`, but should be adjusted in the near future.) A better fix is to handle this specific error in the backend and return an appropriate response, then showing a proper error message in the frontend instead of just displaying "Internal server error." This issue does not significantly affect application performance.

### CODE REVIEW

**Comment by stonith404** [comment]
Hey thank you so much for your PR! I look into it on this weekend. This could take some time because there are 5 really big merge conflicts.

**Comment by stonith404** [comment]
Fixed the merge conflict could you give me access to this PR so I can push the changes? See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) how you can do that.

**Comment by stautonico** [comment]
The checkbox has been checked the entire time. I'm going to try to turn it off and then back on. Sorry about the merge errors btw, idk how that happened, I changed very little code

**Comment by stonith404** [comment]
No problem, I fixed some things while you created the PR. But I think I messed the merge up...

**Comment by stautonico** [comment]
If it's an issue, I can reopen the PR on another branch and reopen the PR.

**Comment by stautonico** [comment]
ofc, I fully believe in contributing to projects you use and enjoy. Fully expect me to open more issues and open more PRs once I deploy this app to my own server and start fully using it

**Pull request merged**
